export const LoginActionType = {
  RESET_LOGIN: 'RESET_LOGIN',
  CHANGE_LOGIN_EMAIL: 'CHANGE_LOGIN_EMAIL',
  SET_LOGIN_EMAIL_VALIDATION: 'SET_LOGIN_EMAIL_VALIDATION',
  SET_LOGIN_EMAIL_DIRTY: 'SET_LOGIN_EMAIL_DIRTY',
  CHANGE_LOGIN_SENHA: 'CHANGE_LOGIN_SENHA',
  SET_LOGIN_SENHA_VALIDATION: 'SET_LOGIN_SENHA_VALIDATION',
  SET_LOGIN_SENHA_DIRTY: 'SET_LOGIN_SENHA_DIRTY'
};

export const PesquisaPassagensActionType = {
  SET_PASSAGENS: 'SET_PASSAGENS',
  RESET_CONSULTA: 'RESET_CONSULTA',
  SET_ACTIVE_PAGE: 'SET_ACTIVE_PAGE',
  SET_PAGE: 'SET_PAGE',
  SET_SORT_FIELD: 'SET_SORT_FIELD',
  SET_SORT_DIRECTION: 'SET_SORT_DIRECTION',
  SET_FILTER_NOME: 'SET_FILTER_NOME',
  SET_FILTER_COMPRA: 'SET_FILTER_COMPRA',
  SET_FILTER_LINHA: 'SET_FILTER_LINHA',
  SET_FILTER_SAIDA: 'SET_FILTER_SAIDA',
  SET_FILTER_POLTRONA: 'SET_FILTER_POLTRONA',
};

export const PerfilUsuarioActionType = {
  CHANGE_NOME: 'CHANGE_NOME',
  SET_NOME_DIRTY: 'SET_NOME_DIRTY',
  SET_NOME_VALIDATION: 'SET_NOME_VALIDATION',
  CHANGE_CPF: 'CHANGE_CPF',
  SET_CPF_DIRTY: 'SET_CPF_DIRTY',
  SET_CPF_VALIDATION: 'SET_CPF_VALIDATION',
  RESET_PERFIL: 'RESET_PERFIL',
  SET_SAVING: 'SET_SAVING',
  SET_EDICAO_HABILITADA: 'SET_EDICAO_HABILITADA'
};

export const LoadingDialogActionType = {
  SET_LOADING_MESSAGE: 'SET_LOADING_MESSAGE',
  SET_LOADING_ICON: 'SET_LOADING_ICON',
  SET_DONE_MESSAGE: 'SET_DONE_MESSAGE',
  SET_DONE_ICON: 'SET_DONE_ICON',
  SET_STATUS: 'SET_STATUS'
}

export const ModalTrajetoActionType = {
  SET_VISIBLE: 'SET_VISIBLE',
}

export const CompraPassagemActionType = {
  SET_CIDADES: 'SET_CIDADES',
  SET_HORARIOS: 'SET_HORARIOS',
  SET_POLTRONAS: 'SET_POLTRONAS',
  RESET_FORM_PASSAGEM: 'RESET_FORM_PASSAGEM',
  CHANGE_NOME: 'CHANGE_NOME',
  SET_NOME_DIRTY: 'SET_NOME_DIRTY',
  SET_NOME_VALIDATION: 'SET_NOME_VALIDATION',
  CHANGE_CPF: 'CHANGE_CPF',
  SET_CPF_DIRTY: 'SET_CPF_DIRTY',
  SET_CPF_VALIDATION: 'SET_CPF_VALIDATION',
  CHANGE_EMAIL: 'CHANGE_EMAIL',
  CHANGE_ORIGEM: 'CHANGE_ORIGEM',
  CHANGE_ORIGEM_VOLTA: 'CHANGE_ORIGEM_VOLTA',
  SET_ORIGEM_DIRTY: 'SET_ORIGEM_DIRTY',
  SET_ORIGEM_VALIDATION: 'SET_ORIGEM_VALIDATION',
  CHANGE_DESTINO: 'CHANGE_DESTINO',
  CHANGE_DESTINO_VOLTA: 'CHANGE_DESTINO_VOLTA',
  SET_DESTINO_DIRTY: 'SET_DESTINO_DIRTY',
  SET_DESTINO_VALIDATION: 'SET_DESTINO_VALIDATION',
  CHANGE_POLTRONA: 'CHANGE_POLTRONA',
  CHANGE_POLTRONA_VOLTA: 'CHANGE_POLTRONA_VOLTA',
  SET_POLTRONA_DIRTY: 'SET_POLTRONA_DIRTY',
  SET_POLTRONA_VALIDATION: 'SET_POLTRONA_VALIDATION',
  CHANGE_DATA: 'CHANGE_DATA',
  CHANGE_DATA_VOLTA: 'CHANGE_DATA_VOLTA',
  CHANGE_HORARIO: 'CHANGE_HORARIO',
  CHANGE_HORARIO_VOLTA: 'CHANGE_HORARIO_VOLTA',
  SET_IDA_VOLTA: 'SET_IDA_VOLTA'
};
