export const LoginActionType = {
  RESET_LOGIN: 'RESET_LOGIN',
  CHANGE_LOGIN_EMAIL: 'CHANGE_LOGIN_EMAIL',
  SET_LOGIN_EMAIL_VALIDATION: 'SET_LOGIN_EMAIL_VALIDATION',
  SET_LOGIN_EMAIL_DIRTY: 'SET_LOGIN_EMAIL_DIRTY',
  CHANGE_LOGIN_SENHA: 'CHANGE_LOGIN_SENHA',
  SET_LOGIN_SENHA_VALIDATION: 'SET_LOGIN_SENHA_VALIDATION',
  SET_LOGIN_SENHA_DIRTY: 'SET_LOGIN_SENHA_DIRTY'
};

export const PesquisaPassagensActionType = {
  SET_PASSAGENS: 'SET_PASSAGENS'
};

export const withLoadingActionType = {
  SET_LOADING: 'SET_LOADING'
};

export const CompraPassagemActionType = {
  SET_CIDADES: 'SET_CIDADES',
  SET_HORARIOS: 'SET_HORARIOS',
  SET_POLTRONAS: 'SET_POLTRONAS',
  RESET_FORM_PASSAGEM: 'RESET_FORM_PASSAGEM',
  CHANGE_NOME: 'CHANGE_NOME',
  SET_NOME_DIRTY: 'SET_NOME_DIRTY',
  SET_NOME_VALIDATION: 'SET_NOME_VALIDATION',
  CHANGE_CPF: 'CHANGE_CPF',
  SET_CPF_DIRTY: 'SET_CPF_DIRTY',
  SET_CPF_VALIDATION: 'SET_CPF_VALIDATION',
  CHANGE_EMAIL: 'CHANGE_EMAIL',
  CHANGE_ORIGEM: 'CHANGE_ORIGEM',
  CHANGE_DESTINO: 'CHANGE_DESTINO',
  CHANGE_POLTRONA: 'CHANGE_POLTRONA',
  SET_POLTRONA_DIRTY: 'SET_POLTRONA_DIRTY',
  SET_POLTRONA_VALIDATION: 'SET_POLTRONA_VALIDATION',
  CHANGE_DATA: 'CHANGE_DATA',
  CHANGE_HORARIO: 'CHANGE_HORARIO'
};
